---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: oskoss/cowboy-pipelines:v1
    tag: 0.1

params:
  PROJECT_NAME:
  HARBOR_FQDN:
  HARBOR_USERNAME:
  HARBOR_PASSWORD:
  TAR_FILENAME:
  
inputs:
  - name: cowboy-pipelines
  - name: chart-tar

run:
  path: cowboy-pipelines/tasks/harbor/upload-helm-chart/task.sh