---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: oskoss/cowboy-pipelines
    tag: 0.1

inputs:
  - name: cowboy-pipelines

run:
  path: cowboy-pipelines/tasks/pks/create-pks-admin/task.sh

params:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  PKS_CLI_USERNAME:
  PKS_CLI_USEREMAIL:
  PKS_CLI_PASSWORD:
  PKS_UAA_FQDN: