---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: oskoss/cowboy-pipelines
    tag: 0.1

params:
  RELEASE_NAME:
  CHART_NAME:
  CHART_VALUES:
  NAMESPACE:
  HELM_REPO_URL:
  HELM_REPO_CA:

inputs:
  - name: cowboy-pipelines
  - name: kube-config
  - name: ca-cert
    optional: true
  
run:
  path: cowboy-pipelines/tasks/k8s/install-helm-chart/task.sh