---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: oskoss/cowboy-pipelines
    tag: 0.1

params:
  CLUSTER_NAME:
  CLUSTER_FQDN:
  DNS_SERVER_IP:

inputs:
  - name: cowboy-pipelines
  - name: pks-config

run:
  path: cowboy-pipelines/tasks/util/set-k8s-master-dynamic-dns/task.sh