---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: oskoss/cowboy-pipelines
    tag: 0.1

inputs:
  - name: cowboy-pipelines

params:
  OPSMAN_CLIENT_ID:
  OPSMAN_CLIENT_SECRET:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:

run:
  path: cowboy-pipelines/tasks/ops-man/apply-changes-pivotal-ops-manager/task.sh