
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: oskoss/cowboy-pipelines
    tag: 0.1

inputs:
  - name: cowboy-pipelines
  - name: pivotal-product

params:
  OPSMAN_CLIENT_ID:
  OPSMAN_CLIENT_SECRET:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:

run:
  path: cowboy-pipelines/tasks/ops-man/stage-pivotal-tile/task.sh