---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: oskoss/cowboy-pipelines
    tag: 0.1

inputs:
  - name: cowboy-pipelines
  - name: kube-config

params:
  TILLER_IMAGE:
  TILLER_IMAGE_TAG:

run:
  path: cowboy-pipelines/tasks/k8s/setup-tiller/task.sh