---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: oskoss/cowboy-pipelines
    tag: 0.1

params:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  VCENTER_HOST:
  VCENTER_USR:
  VCENTER_PWD:
  VCENTER_DATA_CENTER:
  VCENTER_DISK_TYPE:
  EPHEMERAL_STORAGE_NAMES:
  PERSISTENT_STORAGE_NAMES:
  BOSH_VM_FOLDER:
  BOSH_TEMPLATE_FOLDER:
  BOSH_DISK_PATH:
  ICMP_CHECKS_ENABLED:
  MANAGEMENT_NETWORK_NAME:
  MANAGEMENT_VCENTER_NETWORK:
  MANAGEMENT_NW_CIDR:
  MANAGEMENT_EXCLUDED_RANGE:
  MANAGEMENT_NW_DNS:
  MANAGEMENT_NW_GATEWAY:
  MANAGEMENT_NW_AZS:
  WORKLOAD_NETWORK_NAME:
  WORKLOAD_VCENTER_NETWORK:
  WORKLOAD_NW_CIDR:
  WORKLOAD_EXCLUDED_RANGE:
  WORKLOAD_NW_DNS:
  WORKLOAD_NW_GATEWAY:
  WORKLOAD_NW_AZS:
  AZ_1:
  AZ_1_CLUSTER_NAME:
  AZ_1_RP_NAME:
  AZ_2:
  AZ_2_CLUSTER_NAME:
  AZ_2_RP_NAME:
  AZ_3:
  AZ_3_CLUSTER_NAME:
  AZ_3_RP_NAME:
  NTP_SERVERS:
  OPS_DIR_HOSTNAME:
  ENABLE_VM_RESURRECTOR:
  ENABLE_POST_DEPLOY:
  MAX_THREADS:
  NSX_NETWORKING_ENABLED:
  NSX_ADDRESS:
  NSX_USERNAME:
  NSX_PASSWORD:
  NSX_CA_CERTIFICATE:

inputs:
  - name: cowboy-pipelines

run:
  path: cowboy-pipelines/tasks/ops-man/config-pivotal-ops-bosh-director/task.sh