---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: oskoss/cowboy-pipelines:v1
    tag: 0.1

params:
  PROJECT_NAME:
  HARBOR_FQDN:
  HARBOR_USERNAME:
  HARBOR_PASSWORD:
  PUBLIC:
  
inputs:
  - name: cowboy-pipelines

run:
  path: cowboy-pipelines/tasks/harbor/create-harbor-project/task.sh